tsconfig: switch to es6 target
to fix issue with Twirp client for next commit otherwise it returns:

node_modules/twirp-ts/build/twirp/errors.d.ts:28:5 - error TS2425: Class 'Error' defines instance member property 'cause', but extended class 'TwirpError' defines it as instance member function.

Signed-off-by: CrazyMax <1951866+crazy-max@users.noreply.github.com>